name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run doc

      - name: Clean up and prepare docs
        run: |
          # Create a temporary directory
          mkdir -p /tmp/temp_docs
          # Copy only the built documentation
          cp -r docs/* /tmp/temp_docs/
          # Remove all other files
          rm -rf *
          # Move the documentation back
          mv /tmp/temp_docs/* .
          rm -rf /tmp/temp_docs

      - name: Deploy to docs branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.NPM_GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: docs
          commit_message: 'docs: update documentation'